url: "https://www.cal-itp.org"
domain: "www.cal-itp.org"
description: "A state government initiative, Cal-ITP is making riding by rail and bus simpler and more cost-effective—for California transit providers and riders."
title: "Cal-ITP: California Integrated Travel Project"
google_fonts: "https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&family=Raleway:wght@900&display=swap"
theme_background_color: "#b82d28"
theme_color: "#b82d28"
analytics: "G-VCVX2DGPPN"
